collections:
  modules:
    output: true
    permalink: /communication-os/modules/:name

just_the_docs:
  navigation:
    - title: "Modules"
      url: "/communication-os/modules/"
    - title: "Extensions"
      url: "/communication-os/extensions/"
    - title: "Visual Diagrams"
      url: "/communication-os/visual-diagrams/"
    - title: "Framework"
      url: "/communication-os/FRAMEWORK"
    - title: "Principles"
      url: "/communication-os/PRINCIPLES"
    - title: "Methods"
      url: "/communication-os/METHODS"
    - title: "Compiler Architecture"
      url: "/communication-os/COMPILER_ARCHITECTURE"
    - title: "Evaluation"
      url: "/communication-os/EVALUATION"
    - title: "How to Use"
      url: "/communication-os/HOW_TO_USE"
